### ISSUE TITLE
Consolidated Allowance Report Page

### ISSUE THREAD

**Issue by aswinprasanth** [VishnuPriyaSubramanian/ShiftAllowanceAutomation#12]

**Comment by Divyatr** [comment]
done file upload

**Comment by RemyaVenkatesan** [comment]
completed functionality for getallowancedata button in UI

**Comment by VishnuPriyaSubramanian** [comment]
Process allowance function calculated and claim month table values are to processed

**Comment by VishnuPriyaSubramanian** [comment]
Full functionality completed for this page
