### ISSUE TITLE
Db object singleton implementation

### ISSUE THREAD

**Issue by VishnuPriyaSubramanian** [VishnuPriyaSubramanian/ShiftAllowanceAutomation#5]

**Comment by RemyaVenkatesan** [comment]
Singleton implementation has been completed and each of the DAO layer has to use the connection object in the following way.
sample:
public AttendanceDAOOracle() throws ClassNotFoundException, SQLException {
		this.conn = DatabaseConnectionImpl.getInstance().dataBaseConnection();
	}
